export const data = [
  {
    movieTitle: 'The Shawshank Redemption',
    rate: 9.3,
    releaseYear: 1994,
    imageURL: 'URL_imagem_Shawshank_Redemption',
    categories: ['Drama'],
  },
  {
    movieTitle: 'The Godfather',
    rate: 9.2,
    releaseYear: 1972,
    imageURL: 'URL_imagem_The_Godfather',
    categories: ['Crime', 'Drama'],
  },
  {
    movieTitle: 'The Dark Knight',
    rate: 9.0,
    releaseYear: 2008,
    imageURL: 'URL_imagem_The_Dark_Knight',
    categories: ['Action', 'Crime', 'Drama'],
  },
  {
    movieTitle: '12 Angry Men',
    rate: 8.9,
    releaseYear: 1957,
    imageURL: 'URL_imagem_12_Angry_Men',
    categories: ['Crime', 'Drama'],
  },
  {
    movieTitle: "Schindler's List",
    rate: 8.9,
    releaseYear: 1993,
    imageURL: 'URL_imagem_Schindlers_List',
    categories: ['Biography', 'Drama', 'History'],
  },
  {
    movieTitle: 'Forrest Gump',
    rate: 8.8,
    releaseYear: 1994,
    imageURL: 'URL_imagem_Forrest_Gump',
    categories: ['Drama', 'Romance'],
  },
  {
    movieTitle: 'Fight Club',
    rate: 8.8,
    releaseYear: 1999,
    imageURL: 'URL_imagem_Fight_Club',
    categories: ['Drama'],
  },
  {
    movieTitle: 'Inception',
    rate: 8.8,
    releaseYear: 2010,
    imageURL: 'URL_imagem_Inception',
    categories: ['Action', 'Adventure', 'Sci-Fi'],
  },
  {
    movieTitle: 'The Matrix',
    rate: 8.7,
    releaseYear: 1999,
    imageURL: 'URL_imagem_The_Matrix',
    categories: ['Action', 'Sci-Fi'],
  },
  {
    movieTitle: 'Goodfellas',
    rate: 8.7,
    releaseYear: 1990,
    imageURL: 'URL_imagem_Goodfellas',
    categories: ['Biography', 'Crime', 'Drama'],
  },
  {
    movieTitle: 'The Lord of the Rings: The Fellowship of the Ring',
    rate: 8.8,
    releaseYear: 2001,
    imageURL: 'URL_imagem_Lord_of_the_Rings_Fellowship',
    categories: ['Action', 'Adventure', 'Drama'],
  },
  {
    movieTitle: 'Star Wars: Episode V - The Empire Strikes Back',
    rate: 8.7,
    releaseYear: 1980,
    imageURL: 'URL_imagem_Star_Wars_Empire_Strikes_Back',
    categories: ['Action', 'Adventure', 'Fantasy'],
  },
  {
    movieTitle: 'Pulp Fiction',
    rate: 8.9,
    releaseYear: 1994,
    imageURL: 'URL_imagem_Pulp_Fiction',
    categories: ['Crime', 'Drama'],
  },
  {
    movieTitle: 'The Lord of the Rings: The Return of the King',
    rate: 8.9,
    releaseYear: 2003,
    imageURL: 'URL_imagem_Lord_of_the_Rings_Return_of_the_King',
    categories: ['Action', 'Adventure', 'Drama'],
  },
  {
    movieTitle: 'The Silence of the Lambs',
    rate: 8.6,
    releaseYear: 1991,
    imageURL: 'URL_imagem_Silence_of_the_Lambs',
    categories: ['Crime', 'Drama', 'Thriller'],
  },
];
