export const BASE_URL = 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/';

export const data = [
  {
    id: 1,
    movieTitle: 'Um sonho de liberadade',
    rating: 4,
    releaseYear: 1994,
    imageUrl: `${BASE_URL}umX3lBhHoTV7Lsci140Yr8VpXyN.jpg`,
    categories: ['Drama'],
    watched: false,
  },
  {
    id: 2,
    movieTitle: 'Exterminador do Futuro 2',
    rating: 5,
    releaseYear: 1991,
    imageUrl: `${BASE_URL}l5uPlrjcVSI3z3duYeyRAP2E2D0.jpg`,
    categories: ['Sci-Fi', 'Ação'],
    watched: false,
  },
  {
    id: 3,
    movieTitle: 'The Dark Knight',
    rating: 4,
    releaseYear: 2008,
    imageUrl: `${BASE_URL}iGZX91hIqM9Uu0KGhd4MUaJ0Rtm.jpg`,
    categories: ['Ação', 'Drama'],
    watched: false,
  },
  {
    id: 4,
    movieTitle: 'Forrest Gump',
    rating: 4,
    releaseYear: 1994,
    imageUrl: `${BASE_URL}d74WpIsH8379TIL4wUxDneRCYv2.jpg`,
    categories: ['Drama', 'Romance'],
    watched: false,
  },
  {
    id: 5,
    movieTitle: 'Clube da Luta',
    rating: 4,
    releaseYear: 1999,
    imageUrl: `${BASE_URL}r3pPehX4ik8NLYPpbDRAh0YRtMb.jpg`,
    categories: ['Drama'],
    watched: false,
  },
  {
    id: 6,
    movieTitle: 'A Origem',
    rating: 3,
    releaseYear: 2010,
    imageUrl: `${BASE_URL}9e3Dz7aCANy5aRUQF745IlNloJ1.jpg`,
    categories: ['Ação', 'Aventura', 'Sci-Fi'],
    watched: false,
  },
  {
    id: 7,
    movieTitle: 'The Matrix',
    rating: 5,
    releaseYear: 1999,
    imageUrl: `${BASE_URL}lDqMDI3xpbB9UQRyeXfei0MXhqb.jpg`,
    categories: ['Ação', 'Sci-Fi'],
    watched: false,
  },

  {
    id: 8,
    movieTitle: 'O Senhor do Anéis - A Sociedade do Anel',
    rating: 4,
    releaseYear: 2001,
    imageUrl: `${BASE_URL}hi77F0o55uEhZid1eWRp830CRDx.jpg`,
    categories: ['Ação', 'Aventura', 'Drama'],
    watched: false,
  },
  {
    id: 9,
    movieTitle: 'O Senhor do Anéis - O Retorno do Rei',
    rating: 4,
    releaseYear: 2003,
    imageUrl: `${BASE_URL}aMWf3Dir359JzCzxvs7PkWj6ubn.jpg`,
    categories: ['Ação', 'Aventura', 'Drama'],
    watched: false,
  },
  {
    id: 10,
    movieTitle: 'O Silêncio dos Inocentes',
    rating: 3,
    releaseYear: 1991,
    imageUrl: `${BASE_URL}88MzkX0A05z9isFnExmkHx5e1Zq.jpg`,
    categories: ['Crime', 'Drama', 'Suspense'],
    watched: false,
  },
  {
    id: 11,
    movieTitle: 'Cemitério Maldito',
    rating: 5,
    releaseYear: 1989,
    imageUrl: `${BASE_URL}tJDoa8ewjXsWjKSXw1RPQ48fvvg.jpg`,
    categories: ['Terror', 'Drama'],
    watched: false,
  },
  {
    id: 12,
    movieTitle: 'Cemitério Maldito',
    rating: 5,
    releaseYear: 1991,
    imageUrl: `${BASE_URL}tJDoa8ewjXsWjKSXw1RPQ48fvvg.jpg`,
    categories: ['Crime', 'Drama', 'Suspense'],
    watched: false,
  },
  {
    id: 13,
    movieTitle: 'Phantasm II',
    rating: 5,
    releaseYear: 1988,
    imageUrl: `${BASE_URL}pFzE6PoJbCsFJoB00Lf9UbJksRa.jpg`,
    categories: ['Terror', 'Sci-Fi'],
    watched: false,
  },
  // {
  //   id: 14,
  //   movieTitle: 'Os Jovens Pistoleiros',
  //   rating: 5,
  //   releaseYear: 1988,
  //   imageUrl: `${BASE_URL}wsjaEPserDMXR6aNUByepN2jtb2.jpg`,
  //   categories: ['Faroeste', 'Aventura'],
  //   watched: false,
  // },
  // {
  //   id: 15,
  //   movieTitle: 'Desafio no gelo',
  //   rating: 4,
  //   releaseYear: 2004,
  //   imageUrl: `${BASE_URL}dGxGB9bDgzTlnOowHy20XclZJgi.jpg`,
  //   categories: ['Drama', 'História'],
  //   watched: false,
  // },
];
